# Generated by Django 4.2.11 on 2024-03-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='9T Pro', max_length=32, unique=True)),
                ('price', models.PositiveIntegerField(default=2097152)),
                ('color', models.CharField(default='Black', max_length=16)),
                ('display_size', models.SmallIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=90, null=True)),
                ('photos', models.ImageField(upload_to='')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilestore.brand')),
            ],
        ),
    ]
