# Generated by Django 4.2.11 on 2024-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
