# Generated by Django 4.2.11 on 2024-07-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
