# Generated by Django 4.2.11 on 2024-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='محصول فعال'),
        ),
    ]
