# Generated by Django 5.0.2 on 2024-03-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='9T Pro', max_length=32)),
                ('price', models.PositiveIntegerField(default=2097152)),
                ('color', models.CharField(default='Black', max_length=16)),
                ('display_size', models.SmallIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='uploads')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.brand')),
            ],
        ),
    ]
