# Generated by Django 4.2.11 on 2024-03-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_food', '0003_commentwithtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentWithTitle',
        ),
    ]
