# Generated by Django 4.2.11 on 2024-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=75, null=True, unique=True),
        ),
    ]
