# Generated by Django 4.2.11 on 2024-03-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='age',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
