# Generated by Django 4.0.1 on 2022-03-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('signing_date', models.DateTimeField(verbose_name='تاریخ')),
                ('user_type', models.CharField(max_length=1, verbose_name='نوع کاربری')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], default='آقا', max_length=10, verbose_name='جنسیت')),
            ],
            options={
                'ordering': ('signing_date',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null='', verbose_name='نام')),
                ('family', models.CharField(max_length=70, null='', verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('timedate', models.DateTimeField(verbose_name='تاریخ')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.auth', verbose_name='نویسنده')),
            ],
        ),
    ]
