# Generated by Django 4.2.11 on 2024-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_address_id_alter_category_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
