# Generated by Django 4.0.2 on 2022-02-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='free',
            field=models.BooleanField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
